### ISSUE TITLE
Broken Installer

### ISSUE THREAD

**Issue by crocodoyle** [SIMEXP/brainsprite.js#24]
I get the following error when trying to install the Python package, on both Python 3.6 and Python 2.7

`error: Could not find suitable distribution for Requirement.parse('shutil')`

**Comment by pbellec** [comment]
hi @crocodoyle. Looks like python.py is broken. I have not been involved in developing it so far, and I guess it needs a serious push to become usable. But nothing crazy either. 

I know that @surchs has a bunch of code to push, and may end up doing it eventually. Then I will start trying to polish things a bit on my end. Maybe even fix the installer with the help of @poquirion . I don't see that happening before January unfortunately. 

In the meantime I am afraid you won't be able to use the python methods to generate sprites.
  brainsprite.js does work though, if you manage to generate the sprites some other way.

**Comment by crocodoyle** [comment]
Is there a spec somewhere for what the sprites should look like?

**Comment by pbellec** [comment]
There is an example on the website https://simexp.github.io/brainsprite.js
https://github.com/SIMEXP/brainsprite.js/raw/master/tests/sprite_small.jpg

The sprite is composed of sagital slices, ordered left to right and then top to bottom.

There is no restriction on the number of columns, but a roughly square image leads to better compression.

You will need to specify the number of pixels in the Y (width) and Z axis (height) of each image in the sprite.

You can also specify an origin and voxel size. This means that the data should be resampled in order not to have direction cosines.

Pierre

**Comment by pbellec** [comment]
this thread is not directly related to brainsprite.js. Closing now.
