### ISSUE TITLE
doesn't work for images of different dimensions

### ISSUE THREAD

**Issue by jasmainak** [SIMEXP/brainsprite.js#25]
I tried brainsprite.js for the attached image
![mri_contours](https://user-images.githubusercontent.com/15852194/43978059-022bedf4-9cb4-11e8-9748-2745ea5b93a0.png)

and the following code:

```js
<!DOCTYPE html>
<html>

<head>
</head>
<body>
  <div id="div_viewer">
    <canvas id="3Dviewer"> <!-- this is the canvas that will feature the brain slices -->
    <img id="spriteImg" class="hidden" src="mri_contours.png"> <!-- load a hidden version of the sprite image that includes all (sagital) brain slices -->
  </div>

  <script type="text/javascript" src="../assets/jquery-1.9.1/jquery.min.js"></script>  <!-- JQuery is used in this example, line 18, but is not actually used in brainsprite.js --> 
  <script type="text/javascript" src="../assets/brainsprite.js"></script>       
  
  <script> 
    
  // On load: build all figures   
  $( window ).load(function() {
    
    // Create brain slices
    var brain = brainsprite({
      canvas: "3Dviewer", // That is the ID of the canvas to build slices into
      sprite: "spriteImg", // That is the ID of the sprite image that includes all (sagital) brain slices
      origin: {X: 0, Y:0, Z:0}, // Coordinates of the origin of the volume, i.e. point with world coordinates (0,0,0)
      voxelSize: 1, // voxel size. Only isotropic volumes are supported
      onclick: function showCoordinates(brain) { // Show point coordinates
        alert("Slice coordinates: x=" + brain.coordinatesSlice.X + " , y=" + brain.coordinatesSlice.Y + " ,z=" + brain.coordinatesSlice.Z);
      }, 
      nbSlice: {'Y':75, 'Z':75 }
    });
  });
  </script>
</body>
</html>
```

However, the dimensions of the final interactive images are broken. I see this:

![mri_contours](https://user-images.githubusercontent.com/15852194/43978246-9b5a6a0a-9cb4-11e8-9bfa-30b6a61f0670.png)

**Comment by pbellec** [comment]
could it be that the image did not have isotropic voxels?
  quick calculations tells me you have 256 samples along the x axis, but only 75 along the y axis.

If you share the MRI I can try to run it through the sprite generator I am working on in python.

Also, if you are planning to show different overlays? it would be much better to save the anat and the overlay in two separate sprites, and use the overlay feature in brainsprite. The overlay images compress extremely well, and you would only have to ship the anat once. This will cut down the size of your report by a lot.

**Comment by jasmainak** [comment]
Thanks @pbellec. I see the problem now. I fixed it now with this image.
![mri_contours](https://user-images.githubusercontent.com/15852194/43988205-723f67c0-9cfe-11e8-80c5-e384536e3a25.png)
The contours are broken though -- not quite sure if the overlay feature would fix this. 

Hacking time is over for me for now with #NI2018. But I'm at @k-jerbi's lab until end of October, so maybe we can again find a moment to work on this.

**Comment by pbellec** [comment]
not sure what is going on with the contour. 
  As far as I can see, brainsprite renders the volume correctly. 

Could it be that they have been generated or interpolated in 2D?
  You would need to do a 3D resampling with nearest neighbour interpolation before merging the outline on the T1 for it to work.

There is no benefit in using the overlay feature, unless you want to display several overlays on a single T1, in which case you will save loads of space by generating the T1 once and the overlays separately, as the overlay are much, much smaller than the T1.

**Comment by jasmainak** [comment]
> Could it be that they have been generated or interpolated in 2D?
You would need to do a 3D resampling with nearest neighbour interpolation before merging the outline on the T1 for it to work.

yep exactly, this is what @larsoner was hinting at [here](https://github.com/mne-tools/mne-python/issues/5425#issuecomment-411770176). Closing as I don't have bandwidth to work on this right now. Thanks @pbellec for the clarifications !
